[package]
name = "creatorvault"
version = "1.0.0"

[addresses]
creatorvault = "0x033349213be67033ffd596fa85b69ab5c3ff82a508bb446002c8419d549d12c6"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

